# Generated by Django 3.0.2 on 2020-01-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=100)),
                ('user_fk_role', models.IntegerField(blank=True, default=10)),
                ('user_created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regist_user',
            },
        ),
    ]
